<a href="https://colab.research.google.com/github/Harikishan63/Harikishan63/blob/main/Pandas_Refresher_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
#

In [3]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

In [4]:
df = pd.read_csv(url, sep='\t')

In [5]:
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [7]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [8]:
#What was the most ordered item in the choice_description column?
c = df.groupby('item_name')
c= c.sum()
c = c.sort_values(['quantity'], ascending=False)
c.head(1)

,order_id,quantity,choice_description,item_price
item_name,,,,
Chicken Bowl,713926,761,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98 $10.98 $11.25 $8.75 $8.49 $11.25 $8.75 ...

In [9]:
#turning the data into a aflot
dollar = lambda x: float(x[1:-1])
df.item_price = df.item_price.apply(dollar)

In [10]:
#how much was the revenue for the period of dataset
revenue = (df['quantity']*df['item_price']).sum()
print('Revenue was: $' + str(np.round(revenue,2)))

Revenue was: $39237.02

In [11]:
#print a dataframe with only two columns item_name and item_price
orders = df[['item_name','quantity']]

In [12]:
# delete the duplicates in item_name and quantity
filtered = df.drop_duplicates(['item_name','quantity'])
# select only the products with quantity equals to 1
one_prod = filtered[filtered.quantity == 1]
# select only the item_name and item_price columns
price_per_item = one_prod[['item_name', 'item_price']]
# sort the values from the most to less expensive
price_per_item.sort_values(by = "item_price", ascending = False)

                                  item_name  item_price
606                        Steak Salad Bowl       11.89
1229                    Barbacoa Salad Bowl       11.89
1132                    Carnitas Salad Bowl       11.89
7                             Steak Burrito       11.75
168                   Barbacoa Crispy Tacos       11.75
39                            Barbacoa Bowl       11.75
738                       Veggie Soft Tacos       11.25
186                       Veggie Salad Bowl       11.25
62                              Veggie Bowl       11.25
57                           Veggie Burrito       11.25
250                           Chicken Salad       10.98
5                              Chicken Bowl       10.98
8                          Steak Soft Tacos        9.25
554                   Carnitas Crispy Tacos        9.25
237                     Carnitas Soft Tacos        9.25
56                      Barbacoa Soft Tacos        9.25
92                       Steak Crispy Tacos        9.25
664                             Steak Salad        8.99
54                               Steak Bowl        8.99
3750                         Carnitas Salad        8.99
21                         Barbacoa Burrito        8.99
27                         Carnitas Burrito        8.99
33                            Carnitas Bowl        8.99
11                     Chicken Crispy Tacos        8.75
12                       Chicken Soft Tacos        8.75
44                       Chicken Salad Bowl        8.75
1653                    Veggie Crispy Tacos        8.49
16                          Chicken Burrito        8.49
1694                           Veggie Salad        8.49
1414                                  Salad        7.40
510                                 Burrito        7.40
520                            Crispy Tacos        7.40
673                                    Bowl        7.40
298                       6 Pack Soft Drink        6.49
10                      Chips and Guacamole        4.45
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
674       Chips and Mild Fresh Tomato Salsa        3.00
111     Chips and Tomatillo Red Chili Salsa        2.95
233      Chips and Roasted Chili Corn Salsa        2.95
38    Chips and Tomatillo Green Chili Salsa        2.95
3     Chips and Tomatillo-Green Chili Salsa        2.39
300     Chips and Tomatillo-Red Chili Salsa        2.39
191      Chips and Roasted Chili-Corn Salsa        2.39
0              Chips and Fresh Tomato Salsa        2.39
40                                    Chips        2.15
6                             Side of Chips        1.69
263                       Canned Soft Drink        1.25
28                              Canned Soda        1.09
34                            Bottled Water        1.09

In [13]:
#what was the quantity od the most 5expensive item ordered
df.sort_values(by = "item_price", ascending = False).head(5)

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",35.25
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",35.00
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",35.00
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",33.75

In [14]:
#how many times were a veggie Salad Bowl ordered?
df[(df.item_name == "Veggie Salad Bowl")].count()

order_id              18
quantity              18
item_name             18
choice_description    18
item_price            18
dtype: int64

In [15]:
# DATASET 2

In [16]:
df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv")

In [17]:
df.head(10)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
5,Antigua & Barbuda,102,128,45,4.9,NaN
6,Argentina,193,25,221,8.3,SA
7,Armenia,21,179,11,3.8,EU
8,Australia,261,72,212,10.4,OC
9,Austria,279,75,191,9.7,EU

In [18]:
df.groupby('continent').beer_servings.mean()

continent
AF     61.471698
AS     37.045455
EU    193.777778
OC     89.687500
SA    175.083333
Name: beer_servings, dtype: float64

In [19]:
df.groupby('continent').wine_servings.describe()

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

In [20]:
#DATASET3

In [21]:
url='https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv'
crime= pd.read_csv(url)
crime.head()

,Year,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
0,1960,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1,1961,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
2,1962,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800
3,1963,188483000,4109500,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300
4,1964,191141000,4564600,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800

In [22]:
#Converting the type of the column year to datetime64
crime.Year = pd.to_datetime(crime.Year, format='%Y')
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                55 non-null     datetime64[ns]
 1   Population          55 non-null     int64
 2   Total               55 non-null     int64
 3   Violent             55 non-null     int64
 4   Property            55 non-null     int64
 5   Murder              55 non-null     int64
 6   Forcible_Rape       55 non-null     int64
 7   Robbery             55 non-null     int64
 8   Aggravated_assault  55 non-null     int64
 9   Burglary            55 non-null     int64
 10  Larceny_Theft       55 non-null     int64
 11  Vehicle_Theft       55 non-null     int64
dtypes: datetime64[ns](1), int64(11)
memory usage: 5.3 KB

In [23]:
#Set the Year column as the index of the dataframe¶
crime.set_index('Year', inplace=True)
crime.head()

,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,,
1960-01-01,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1961-01-01,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
1962-01-01,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800
1963-01-01,188483000,4109500,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300
1964-01-01,191141000,4564600,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800

In [24]:
#grouping the year by decades and sum the values
crimes = crime.resample('10AS').sum()

# Uses resample to get the max value only for the "population column"
population = crime['Population'].resample('10AS').max()

# Updating the "Population" column with the "population" series
crimes['Population'] = population

crimes

,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,,
1960-01-01,201385000,49295900,4134930,45160900,106180,236720,1633510,2158520,13321100,26547700,5292100
1970-01-01,220099000,100991600,9607930,91383800,192230,554570,4159020,4702120,28486000,53157800,9739900
1980-01-01,248239000,131123369,14074328,117048900,206439,865639,5383109,7619130,33073494,72040253,11935411
1990-01-01,272690813,136582146,17527048,119053499,211664,998827,5748930,10568963,26750015,77679366,14624418
2000-01-01,307006550,115012044,13968056,100944369,163068,922499,4230366,8652124,21565176,67970291,11412834
2010-01-01,318857056,50167967,6072017,44095950,72867,421059,1749809,3764142,10125170,30401698,3569080

In [25]:
crimes.head()

,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,,
1960-01-01,201385000,49295900,4134930,45160900,106180,236720,1633510,2158520,13321100,26547700,5292100
1970-01-01,220099000,100991600,9607930,91383800,192230,554570,4159020,4702120,28486000,53157800,9739900
1980-01-01,248239000,131123369,14074328,117048900,206439,865639,5383109,7619130,33073494,72040253,11935411
1990-01-01,272690813,136582146,17527048,119053499,211664,998827,5748930,10568963,26750015,77679366,14624418
2000-01-01,307006550,115012044,13968056,100944369,163068,922499,4230366,8652124,21565176,67970291,11412834

In [26]:
#Return the first 3 rows of the dataframe df.
df = crime

In [27]:
df.iloc[:3]

,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,,
1960-01-01,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1961-01-01,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
1962-01-01,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800

In [29]:
df.loc[:, ['Murder', 'Robbery']].head()

            Murder  Robbery
Year
1960-01-01    9110   107840
1961-01-01    8740   106670
1962-01-01    8530   110860
1963-01-01    8640   116470
1964-01-01    9360   130390

**bold text**# Functioning with basic operations

In [31]:
#selecting the data in rows[3,4,7] and in columns['Murder', 'Robbery']
df.loc[df.index[[3,4,7]], ['Murder', 'Robbery']]

            Murder  Robbery
Year
1963-01-01    8640   116470
1964-01-01    9360   130390
1967-01-01   12240   202910

In [33]:
#Selecting only the rows where the number of murder is greater than 24,000
df[df.Murder > 24000]

,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,,
1991-01-01,252177000,14872900,1911770,12961100,24700,106590,687730,1092740,3157200,8142200,1661700
1993-01-01,257908000,14144800,1926020,12218800,24530,106010,659870,1135610,2834800,7820900,1563100

In [37]:
df[df['Murder'].between(20000, 24000)]

,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,,
1974-01-01,211392000,10253400,974720,9278700,20710,55400,442400,456210,3039200,5262500,977100
1975-01-01,213124000,11292400,1039710,10252700,20510,56090,470500,492620,3265300,5977700,1009600
1979-01-01,220099000,12249500,1208030,11041500,21460,76390,480700,629480,3327700,6601000,1112800
1980-01-01,225349264,13408300,1344520,12063700,23040,82990,565840,672650,3795200,7136900,1131700
1981-01-01,229146000,13423800,1361820,12061900,22520,82500,592910,663900,3779700,7194400,1087800
1982-01-01,231534000,12974400,1322390,11652000,21010,78770,553130,669480,3447100,7142500,1062400
1986-01-01,240132887,13211869,1489169,11722700,20613,91459,542775,834322,3241410,7257153,1224137
1987-01-01,242282918,13508700,1483999,12024700,20096,91110,517704,855088,3236184,7499900,1288674
1988-01-01,245807000,13923100,1566220,12356900,20680,92490,542970,910090,3218100,7705900,1432900
1989-01-01,248239000,14251400,1646040,12605400,21500,94500,578330,951710,3168200,7872400,1564800
1990-01-01,248709873,14475600,1820130,12655500,23440,102560,639270,1054860,3073900,7945700,1635900
1992-01-01,255082000,14438200,1932270,12505900,23760,109060,672480,1126970,2979900,7915200,1610800
1994-01-01,260341000,13989500,1857670,12131900,23330,102220,618950,1113180,2712800,7879800,1539300
1995-01-01,262755000,13862700,1798790,12063900,21610,97470,580510,1099210,2593800,7997700,1472400

In [38]:
#Calculating the Mean murder for each different year in df
df.groupby('Year').Murder.mean()

Year
1960-01-01     9110.0
1961-01-01     8740.0
1962-01-01     8530.0
1963-01-01     8640.0
1964-01-01     9360.0
1965-01-01     9960.0
1966-01-01    11040.0
1967-01-01    12240.0
1968-01-01    13800.0
1969-01-01    14760.0
1970-01-01    16000.0
1971-01-01    17780.0
1972-01-01    18670.0
1973-01-01    19640.0
1974-01-01    20710.0
1975-01-01    20510.0
1976-01-01    18780.0
1977-01-01    19120.0
1978-01-01    19560.0
1979-01-01    21460.0
1980-01-01    23040.0
1981-01-01    22520.0
1982-01-01    21010.0
1983-01-01    19310.0
1984-01-01    18690.0
1985-01-01    18980.0
1986-01-01    20613.0
1987-01-01    20096.0
1988-01-01    20680.0
1989-01-01    21500.0
1990-01-01    23440.0
1991-01-01    24700.0
1992-01-01    23760.0
1993-01-01    24530.0
1994-01-01    23330.0
1995-01-01    21610.0
1996-01-01    19650.0
1997-01-01    18208.0
1998-01-01    16914.0
1999-01-01    15522.0
2000-01-01    15586.0
2001-01-01    16037.0
2002-01-01    16229.0
2003-01-01    16528.0
2004-01-01    16148.0
2005-01-01    16740.0
2006-01-01    17030.0
2007-01-01    16929.0
2008-01-01    16442.0
2009-01-01    15399.0
2010-01-01    14772.0
2011-01-01    14661.0
2012-01-01    14866.0
2013-01-01    14319.0
2014-01-01    14249.0
Name: Murder, dtype: float64

In [40]:
#sort df first by the values in the 'Murder' in descending order,
#then by the values in the 'Violent' column in ascendng order.
df.sort_values(by=['Murder', 'Violent'], ascending=[False, True])

,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,,
1991-01-01,252177000,14872900,1911770,12961100,24700,106590,687730,1092740,3157200,8142200,1661700
1993-01-01,257908000,14144800,1926020,12218800,24530,106010,659870,1135610,2834800,7820900,1563100
1992-01-01,255082000,14438200,1932270,12505900,23760,109060,672480,1126970,2979900,7915200,1610800
1990-01-01,248709873,14475600,1820130,12655500,23440,102560,639270,1054860,3073900,7945700,1635900
1994-01-01,260341000,13989500,1857670,12131900,23330,102220,618950,1113180,2712800,7879800,1539300
1980-01-01,225349264,13408300,1344520,12063700,23040,82990,565840,672650,3795200,7136900,1131700
1981-01-01,229146000,13423800,1361820,12061900,22520,82500,592910,663900,3779700,7194400,1087800
1995-01-01,262755000,13862700,1798790,12063900,21610,97470,580510,1099210,2593800,7997700,1472400
1989-01-01,248239000,14251400,1646040,12605400,21500,94500,578330,951710,3168200,7872400,1564800
1979-01-01,220099000,12249500,1208030,11041500,21460,76390,480700,629480,3327700,6601000,1112800
1982-01-01,231534000,12974400,1322390,11652000,21010,78770,553130,669480,3447100,7142500,1062400
1974-01-01,211392000,10253400,974720,9278700,20710,55400,442400,456210,3039200,5262500,977100
1988-01-01,245807000,13923100,1566220,12356900,20680,92490,542970,910090,3218100,7705900,1432900
1986-01-01,240132887,13211869,1489169,11722700,20613,91459,542775,834322,3241410,7257153,1224137
1975-01-01,213124000,11292400,1039710,10252700,20510,56090,470500,492620,3265300,5977700,1009600
1987-01-01,242282918,13508700,1483999,12024700,20096,91110,517704,855088,3236184,7499900,1288674
1996-01-01,265228572,13493863,1688540,11805300,19650,96250,535590,1037050,2506400,7904700,1394200
1973-01-01,209851000,8718100,875910,7842200,19640,51400,384220,420650,2565500,4347900,928800
1978-01-01,218059000,11209000,1085550,10123400,19560,67610,426930,571460,3128300,5991000,1004100
1983-01-01,233981000,12108600,1258090,10850500,19310,78920,506570,653290,3129900,6712800,1007900
1977-01-01,216332000,10984500,1029580,9955000,19120,63500,412610,534350,3071500,5905700,977700
1985-01-01,238740000,12431400,1328800,11102600,18980,88670,497870,723250,3073300,6926400,1102900
1976-01-01,214659000,11349700,1004210,10345500,18780,57080,427810,500530,3108700,6270800,966000
1984-01-01,236158000,11881800,1273280,10608500,18690,84230,485010,685350,2984400,6591900,1032200
1972-01-01,208230000,8248800,834900,7413900,18670,46850,376290,393090,2375500,4151200,887200
1997-01-01,267637000,13194571,1634770,11558175,18208,96153,498534,1023201,2460526,7743760,1354189
1971-01-01,206212000,8588200,816500,7771700,17780,42260,387700,368760,2399300,4424200,948200
2006-01-01,299398484,11401511,1418043,9983568,17030,92757,447403,860853,2183746,6607013,1192809
2007-01-01,301621157,11251828,1408337,9843481,16929,90427,445125,855856,2176140,6568572,1095769
1998-01-01,270296000,12475634,1531044,10944590,16914,93103,446625,974402,2329950,7373886,1240754
2005-01-01,296507061,11565499,1390745,10174754,16740,94347,417438,862220,2155448,6783447,1235859
2003-01-01,290690788,11826538,1383676,10442862,16528,93883,414235,859030,2154834,7026802,1261226
2008-01-01,304374846,11160543,1392628,9767915,16442,90479,443574,842134,2228474,6588046,958629
2002-01-01,287973924,11878954,1423677,10455277,16229,95235,420806,891407,2151252,7057370,1246646
2004-01-01,293656842,11679474,1360088,10319386,16148,95089,401470,847381,2144446,6937089,1237851
2001-01-01,285317559,11876669,1439480,10437480,16037,90863,423557,909023,2116531,7092267,1228391
1970-01-01,203235298,8098000,738820,7359200,16000,37990,349860,334970,2205000,4225800,928400
2000-01-01,281421906,11608072,1425486,10182586,15586,90178,408016,911706,2050992,6971590,1160002
1999-01-01,272690813,11634378,1426044,10208334,15522,89411,409371,911740,2100739,6955520,1152075
2009-01-01,307006550,10762956,1325896,9337060,15399,89241,408742,812514,2203313,6338095,795652
2012-01-01,313873685,10219059,1217067,9001992,14866,85141,355051,762009,2109932,6168874,723186
2010-01-01,309330219,10363873,1251248,9112625,14772,85593,369089,781844,2168457,6204601,739565
1969-01-01,201385000,7410900,661870,6749000,14760,37170,298850,311090,1981900,3888600,878500
2011-01-01,311587816,10258774,1206031,9052743,14661,84175,354772,752423,2185140,6151095,716508
2013-01-01,316497531,9850445,1199684,8650761,14319,82109,345095,726575,1931835,6018632,700294
2014-01-01,318857056,9475816,1197987,8277829,14249,84041,325802,741291,1729806,5858496,689527
1968-01-01,199399000,6720200,595010,6125200,13800,31670,262840,286700,1858900,3482700,783600
1967-01-01,197457000,5903400,499930,5403500,12240,27620,202910,257160,1632100,3111600,659800
1966-01-01,195576000,5223500,430180,4793300,11040,25820,157990,235330,1410100,2822000,561200
1965-01-01,193526000,4739400,387390,4352000,9960,23410,138690,215330,1282500,2572600,496900
1964-01-01,191141000,4564600,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800
1960-01-01,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1961-01-01,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
1963-01-01,188483000,4109500,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300
1962-01-01,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800